### ISSUE TITLE
StRefMultCorr instantiation

### ISSUE THREAD

**Issue by MustafaMustafa** [MustafaMustafa/auau200GeVRun14Ana#10]
Hello @GuannanXie, 

Why do you pass the gRefMultCorr as a parameter to the ctor and then you don't use it but create a new instance?

https://github.com/MustafaMustafa/auau200GeVRun14Ana/blob/master/StRoot/StPicoD0AnaMaker/StPicoD0AnaMaker.cxx#L66

**Comment by GuannanXie** [comment]
Yes, you are right, there is no need to define it again,It's already removed from code.

**Comment by MustafaMustafa** [comment]
Thanks,

--Mustafa
