### ISSUE TITLE
Review usage of RefMultCorr

### ISSUE THREAD

**Issue by MustafaMustafa** [MustafaMustafa/auau200GeVRun14Ana#15]
Hi @GuannanXie, 

Can you review how I load StRefMultCorr in
StRoot/macros/run_StMcAnalysisMaker.C
and how I use it in
StRoot/StMcAnalysisMaker/StMcAnalysisMaker.cxx
?

Thanks,

**Comment by GuannanXie** [comment]
Hi Mustafa,
I Just have a quick look at, It's should be fine.
Actually, this method is better than what we did for D0Ana.

Thanks,

**Comment by MustafaMustafa** [comment]
Thank you for the prompt response!
